<?php
// Balise list generated by RBC
$BL_PT2_FILE = "/home/jabe/Desktop/Projekter/Git/WinterTrain/WaySide/SiteData/W57/PT2.php";
$BL_GENERATION_TIME = "2020-10-29 22:46:35";

// -------------------------------------------------- Full balise List
$baliseList = [
"BG03" => ["ID" => "76:00:0D:1A:2E",
           "dynName" => true],
"BG02" => ["ID" => "74:00:10:F3:3E",
           "dynName" => true],
"BG01" => ["ID" => "1E:00:57:5B:28",
           "dynName" => true],
"BG11" => ["ID" => "1F:00:4D:6D:73",
           "dynName" => true],
"BG10" => ["ID" => "74:00:11:07:0B",
           "dynName" => true],
"BG9" => ["ID" => "73:00:56:D9:B2",
           "dynName" => true],
"BG8" => ["ID" => "1E:00:EC:F9:E1",
           "dynName" => true],
"BG7" => ["ID" => "1E:00:B0:50:33",
           "dynName" => true],
"BG6" => ["ID" => "1E:00:EA:E8:E9",
           "dynName" => true],
"BG5" => ["ID" => "1F:00:61:E5:87",
           "dynName" => true],
"BG04" => ["ID" => "73:00:6E:C8:15",
           "dynName" => true],
];
?>